= Guacamole dotool
:proj-name: guacamole-dotool
:npm-name: {proj-name}
:gh-name: jirutka/{proj-name}

ifdef::env-github[]
image:https://github.com/{gh-name}/workflows/CI/badge.svg[CI Workflow, link=https://github.com/{gh-name}/actions?query=workflow%3A%22CI%22]
image:https://img.shields.io/npm/v/{npm-name}.svg[npm Version, link="https://www.npmjs.org/package/{npm-name}"]
endif::env-github[]

A command-line https://guacamole.apache.org/[Guacamole] client and TypeScript/JavaScript library for headless scripting.
It’s exactly like https://github.com/sibson/vncdotool[vncdotool] or https://github.com/jordansissel/xdotool[xdotool], but over the Guacamole protocol.


== Installation

=== Using npm

[source, subs="+attributes"]
npm install --global {npm-name}

*Warning:* The https://github.com/Automattic/node-canvas[canvas] package downloads pre-built native libraries (cairo, pango, libjpeg…) from npmjs.com by default.
If you want to build it from source instead (highly recommended), use option `--build-from-source`.
See https://github.com/Automattic/node-canvas#installation[node-canvas installation] for details.



== Usage

=== Command line

[source, sh]
----
guacamole-dotool --url wss://example.org/guacamole -- \
  key Cmd+t pause 2 type 'echo "Hello, world!"' key Enter pause 0.5 capture screenshot.png
----

Run `guacamole-dotool --help` to learn more.


=== TypeScript / JavaScript

[source, ts, subs="+attributes"]
----
import { Client, setDomGlobals } from '{npm-name}'

// Set canvas, jsdom and ws to the global context.
setDomGlobals()

// Connect to Guacamole via WebSocket.
const c = await Client.connect('wss://example.org/guacamole')

// Run commands...
await c.keysPress('Cmd', 't')
await c.pause(2)
await c.type('echo "Hello, world!"')
await c.keysPress('Enter')
await c.pause(0.5)
await c.captureScreenToFile('screenshot.png')

c.disconnect()
----

See link:src/client.ts[] to learn more.


== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
For the full text of the license, see the link:LICENSE[LICENSE] file.
