on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        node-version:
          - lts/-1
          - lts/*
          - latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm clean-install
      - run: npm run build
      - run: npm run lint

  publish:
    name: Publish on npmjs
    needs: test
    if: startsWith(github.ref, 'refs/tags/v') && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install asciidoctor pandoc

      - uses: actions/checkout@v4

      - run: npm clean-install

      - run: npm run build

      - name: Set up .npmrc file
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
