name: CI
on:
  push:
  pull_request:
  schedule:
    # Run every week on Saturday midnight.
    - cron: 0 0 * * 6

jobs:
  test:
    strategy:
      matrix:
        node-version:
          - lts/-1
          - lts/*
          - latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: sudo apt-get install -y libpango1.0-dev libgif-dev

      - run: npm clean-install
      - run: npm run build
      - run: npm run lint
      - run: node lib/cli.js --help

  bundle-alpine:
    name: Build bundle on Alpine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup latest Alpine Linux
        uses: jirutka/setup-alpine@v1
        with:
          packages: >
            build-base
            giflib-dev
            nodejs
            npm
            pango-dev
            pixman-dev

      - run: npm clean-install --build-from-source
        shell: alpine.sh {0}

      - name: npm run bundle
        run: |
          npm run bundle
          ls -lah dist/
          ls -lah dist/libs
        shell: alpine.sh {0}

      - name: guacamole-dotool --help
        run: |
          rm -rf node_modules package.json
          ./dist/guacamole-dotool.mjs --help
        shell: alpine.sh {0}

  bundle-ubuntu:
    name: Build bundle on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies for building canvas
        run: sudo apt-get install libcairo2-dev libgif-dev libjpeg-dev libpango1.0-dev librsvg2-dev

      - run: npm clean-install --build-from-source

      - name: npm run bundle
        run: |
          npm run bundle
          ls -lah dist/
          ls -lah dist/libs

      - name: guacamole-dotool --help
        run: |
          rm -rf node_modules package.json
          ./dist/guacamole-dotool.mjs --help

  publish:
    name: Publish on npmjs
    needs: test
    if: startsWith(github.ref, 'refs/tags/v') && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install asciidoctor pandoc

      - uses: actions/checkout@v4

      - run: npm clean-install

      - run: npm run build

      - name: Set up .npmrc file
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
