name: Release
on:
  release:
    types: [published]

jobs:
  npmjs:
    name: Publish on npmjs
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - run: sudo apt-get install -y asciidoctor pandoc

      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - run: npm clean-install

      - run: npm run build

      - run: npm publish --provenance --access public
